---
title: "git_01"
author: "Melissa Sanchez"
date: "Summer 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twinkle, twinkle, little bat!    
How I wonder what you're at!    

Up above the world you fly,    
Like a tea tray in the sky.    

Twinkle, twinkle, little bat!    
How I wonder what you're at!    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,    
Some say in ice.    
From what I've tasted of desire.     
I hold with those who favor fire.      
But if it had to perish twice,      
I think I know enough of hate.     
To know that for destruction ice.     
Is also great.     


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

“The sun was shining on the sea,    
Shining with all his might:    
He did his very best to make.     
The billows smooth and bright —    
And this was odd, because it was.       
The middle of the night.    
  
The moon was shining sulkily,    
Because she thought the sun.     
Had got no business to be there.     
After the day was done —    
“It’s very rude of him,” she said,    
”To come and spoil the fun.”    

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

One fish.   
Two fish.   
Red fish.    
Blue fish.    
Black fish.   
Blue fish.   
Old fish.   
New fish.    
This one has a little star.    
This one has a little car.    
Say! What a lot.   
Of fish there are.    
Yes. Some are red. And some are blue.    
Some are old. And some are new.    
Some are sad.    
And some are glad.    
And some are very, very bad.    
Why are they.   
Sad and glad and bad?    
I do not know.    
Go ask your dad.    
Some are thin.    
And some are fat.    
The fat one has.   
A yellow hat.    
From there to here, from here to there,    
Funny things.   
Are everywhere.    
